#!/usr/bin/env python3
"""
Market Pulse — GitHub Actions dashboard updater
Reads data.json (pushed to this repo by Apps Script each Friday via GitHub API)
and injects it into index.html as SAMPLE_DATA / SAMPLE_RAW.

No public Google Sheet required.
"""

import json
import re
from datetime import datetime, timezone

DATA_FILE      = "data.json"
DASHBOARD_FILE = "index.html"


def build_sample_data(signals):
    entries = []
    for r in signals:
        if not r.get("company") or not r.get("headline"):
            continue
        source_urls = r.get("source_urls") or ""
        if isinstance(source_urls, list):
            source_urls = "\n".join(source_urls)
        entry = (
            "  { "
            + f"date:{json.dumps(str(r.get('date', '')))}, "
            + f"company:{json.dumps(str(r.get('company', '')))}, "
            + f"website:{json.dumps(str(r.get('website', '')))}, "
            + f"tier:{json.dumps(str(r.get('tier', '')))}, "
            + f"region:{json.dumps(str(r.get('region', '')))}, "
            + f"signal_type:{json.dumps(str(r.get('signal_type', '')))}, "
            + f"importance:{json.dumps(str(r.get('importance', '')))}, "
            + f"headline:{json.dumps(str(r.get('headline', '')))}, "
            + f"summary:{json.dumps(str(r.get('summary', '')))}, "
            + f"source_urls:{json.dumps(source_urls)}"
            + " }"
        )
        entries.append(entry)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = (
        ["// Auto-generated by GitHub Actions on " + now, "const SAMPLE_DATA = ["]
        + [e + ("," if i < len(entries) - 1 else "") for i, e in enumerate(entries)]
        + ["];"]
    )
    return "\n".join(lines)


def build_sample_raw(archive):
    entries = []
    for r in archive:
        if not r.get("company") or not r.get("title"):
            continue
        entry = (
            "  { "
            + f"'Run Date':{json.dumps(str(r.get('run_date', '')))}, "
            + f"'Article Date':{json.dumps(str(r.get('article_date', '')))}, "
            + f"'Company':{json.dumps(str(r.get('company', '')))}, "
            + f"'Tier':{json.dumps(str(r.get('tier', '')))}, "
            + f"'Category':{json.dumps(str(r.get('category', '')))}, "
            + f"'Region':{json.dumps(str(r.get('region', '')))}, "
            + f"'Title':{json.dumps(str(r.get('title', '')))}, "
            + f"'Summary':{json.dumps(str(r.get('summary', '')))}, "
            + f"'URL':{json.dumps(str(r.get('url', '')))}, "
            + f"'Language':{json.dumps(str(r.get('language', '')))} "
            + "}"
        )
        entries.append(entry)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = (
        ["// Auto-generated by GitHub Actions on " + now, "const SAMPLE_RAW = ["]
        + [e + ("," if i < len(entries) - 1 else "") for i, e in enumerate(entries)]
        + ["];"]
    )
    return "\n".join(lines)


def inject_into_html(html, sample_data_js, sample_raw_js):
    html = re.sub(
        r"(?:// Auto-generated[^\n]*\n)?const SAMPLE_DATA = \[[\s\S]*?\];",
        sample_data_js, html)
    html = re.sub(
        r"(?:// Auto-generated[^\n]*\n)?const SAMPLE_RAW = \[[\s\S]*?\];",
        sample_raw_js, html)
    return html


def main():
    print("Reading " + DATA_FILE + "...")
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    signals = data.get("signals", [])
    archive = data.get("archive", [])
    print("  " + str(len(signals)) + " signals, " + str(len(archive)) + " archive articles")

    sample_data_js = build_sample_data(signals)
    sample_raw_js  = build_sample_raw(archive)

    print("Updating " + DASHBOARD_FILE + "...")
    with open(DASHBOARD_FILE, "r", encoding="utf-8") as f:
        html = f.read()

    updated = inject_into_html(html, sample_data_js, sample_raw_js)

    with open(DASHBOARD_FILE, "w", encoding="utf-8") as f:
        f.write(updated)

    print("Done — " + DASHBOARD_FILE + " updated successfully")


if __name__ == "__main__":
    main()
